name: Stats  #Nombre de la github accion 

on: #lo que hara cuando le diga, en este caso hara cada que se haga un push en la rama "main"
  push:
    branches: [main]

jobs: 
  build: 
    runs-on: ubuntu-latest

    permissions: 
      contents: write

    steps:  #acciones
      - name: Checkout repositorio 
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with: 
         python-version: '3.12.10'
         
      - name: Run Script python
        run: python ./Roadmap/stats.py  #ruta del archivo que se va a correr

      - name: Commit and Push changes 
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
         commit_message: Update stats
